### ISSUE TITLE
Only one homeserver option shouldn't show a dropdown

### ISSUE THREAD

**Issue by viasux** [ajbura/cinny#1038]
### Describe the bug

When you choose only one homeserver as an option in cinny's config file, as well as making it so users can't type in the homeserver box, there shouldn't be a dropdown at all.

![image](https://user-images.githubusercontent.com/47131867/209434931-abb04c1b-5e79-4e2b-b9ca-cf0fa1a3f9dd.png)

### Reproduction

1. Install cinny
2. Configure cinny to only have one homeserver and not allow users to set their own
3. See issue on signup

### Expected behavior

I expect there to not be a dropdown on the right for homeservers when there's only one option

### Platform and versions

```shell
1. OS: Windows 10
2. Browser: Librewolf
3. Cinny Version: 2.2.2
4. Matrix Homeserver: kitty.social
```

**Comment by centralscrutinizer21** [comment]
Can i ask how you edited your config.json in order to achieve this? When I put my server it always fall back to matrix.org

**Comment by kfiven** [comment]
You probably missing a comma somewhere @centralscrutinizer21 .json is very strict about that.

**Comment by centralscrutinizer21** [comment]
@kfiven can you post an example of a config.json set to show a single server?

**Comment by ajbura** [comment]
@centralscrutinizer21 
```json
{
  "defaultHomeserver": 0,
  "homeserverList": [
    "xyz.server"
  ],
  "allowCustomHomeservers": true
}
```

**Comment by Domoel** [comment]
Could someone explain how to apply the config.json if one is using a docker compose setup? I tried to mount the file directly to the root directory of the docker directory with hte following entry:

```
    volumes:
      - /volume2/docker/test/config.json:/config.json
```

However it does not work. Could somebody explain me how to deal with this issue?

Edit: I was able to fix the issue. Instead of mounting it directly with `./cinny/config.json:/config.json `one must mount the file into  the following directory `./cinny/config.json:/app/config.json`. After cookie deletion everything was there.
