### ISSUE TITLE
"All rooms" option in sidebar

### ISSUE THREAD

**Issue by vijfhoek** [ajbura/cinny#1080]
### Describe the problem

I have heavily categorised my Matrix account in spaces, but that means that I have to do a lot of clicks to check my unread messages.

### Describe the solution you'd like

It would be nice if there could be an "All rooms" option in the left sidebar, under "Home" and "People". Another option would be having a setting in "Home" to show all rooms there (instead of only the rooms that aren't in spaces), just like Element.

### Alternatives considered

Creating a space with all rooms, but that would require manually adding every room to the space every time I join one

**Comment by kfiven** [comment]
Have you tried 'Categorize subspace' option in space options?

**Comment by LinuxinaBit** [comment]
I don’t believe there’s an option for that in the Home tab, so it can’t apply to all spaces.

A dedicated button would probably be better in either case, because uncategorized rooms could easily be buried, but an extra button does add unnecessary clutter.

I think the best option is a toggle at the top of the the “Pin spaces” menu to turn on the “All rooms” button.

**Comment by kfiven** [comment]
> heavily categorised my Matrix account in spaces

Categorize subspaces is exactly for that, closing as there's nothing is to done here.
