### ISSUE TITLE
Use formatted_body to parse markdown

### ISSUE THREAD

**Issue by ajbura** [ajbura/cinny#133]
@tulir:maunium.net

formatting: don't parse `body` as markdown, use the html in `formatted_body` (https://matrix.org/docs/spec/client_server/r0.6.1#m-room-message-msgtypes)

**Comment by Salamandar** [comment]
That will also allow displaying links, colored text and such :D

**Comment by samueldr** [comment]
It does; I think it makes custom emoticons work as the receiving end too if I'm not mistaken

![image](https://user-images.githubusercontent.com/132835/142498516-f2a1ea17-b785-43ad-8f9d-c06419d22a21.png)

`mxc://` images just work. (The clippit in the message here is done with an `mxc://` image, colors and formatting comes from `formatted_body` shenanigans sent from another client.)

It changes nothing about *sending* anything fancy with the current state. I still need to fix at least one issue I've observed, but I've been dogfooding the WIP work fo over a week ~~and only newlines in formatted body seems to be causing issues~~.

Huh... just tested against element and the issue seems to be on the sending side of things. I'll have to investigate, but that means I still haven't seen an issue.
