### ISSUE TITLE
Registration disabled, hide register and login form except for OIDC providers

### ISSUE THREAD

**Issue by samip5** [ajbura/cinny#146]
#### Describe the bug
When a Synapse Matrix server has disabled registration, the links should be hidden for registration aswell as hide login input fields but show OIDC authentication provider links.

#### To Reproduce
1. Deploy Matrix Synapse with OIDC auth only enabled, registration disabled.
2. Deploy Cinny, change default HS url.
3. Go to Cinny and see that OIDC provider link has appeared but the login from and registration link is still visiable.

#### Expected behavior
The login input fields would be hidden and registration link too so only shown would be OIDC/SSO provider login method.

#### Screenshots

![image](https://user-images.githubusercontent.com/1703002/138576136-5a2ff56f-4402-4887-990c-6f9fb9b50b0d.png)

#### Additional context
Element does it like this:
![image](https://user-images.githubusercontent.com/1703002/138576146-0ce1a751-3e08-4384-8515-49f3f924e07a.png)

**Comment by simonwuelker** [comment]
@ajbura why is this closed? It is not fixed.
![image](https://user-images.githubusercontent.com/58120269/150689359-bd803435-760d-4855-ae42-9bf659717558.png)

**Comment by ajbura** [comment]
@Wuelle It has been fixed. Why you think it’s not fixed?

**Comment by simonwuelker** [comment]
Because this Registration link
![grafik](https://user-images.githubusercontent.com/58120269/150728161-8308b406-4bae-44ab-adde-51b8169df326.png)
still shows up, despite registration being disabled. Once you click it, you get
![grafik](https://user-images.githubusercontent.com/58120269/150728231-dca53e41-0b95-4470-917d-671f5b7426ec.png)
Two things: 
* In the first screenshot, the "Dont have an account? Register" link should not appear.
* In the second screenshot, the "Already have an account? Login" link should not appear.
(This is part of the issue the OP was referring to, so i did not open a new issue and commented on this one instead)
I am using v1.6.1

**Comment by ajbura** [comment]
@Wuelle OP was referring to hide login and registration **_form_** not these links.

The reason we’ve kept these links because, 
a). User can know that registrations are disabled on xyz homeserver when they are on login page.
b). And if someone goes to registration page then can come back on login page.

**Comment by simonwuelker** [comment]
> OP was referring to hide login and registration form not these links.

from the original issue:
> The login input fields would be hidden and registration link too so only shown would be OIDC/SSO provider login method.

If you already thought about removing the link and decided against it, fair enough.
IMO the better way of letting the user know registration is disabled would be by not showing a registration link.
