### ISSUE TITLE
Decrypt old messages in E2EE room I joined

### ISSUE THREAD

**Issue by filipesmedeiros** [ajbura/cinny#1561]
### Describe the problem

When I join a room that's E2EE (with the setting that everyone should be able to see the room's history), I can't see history. All messages say "Unable to decrypt message"

### Describe the solution you'd like

I'd like to be able to see the history

### Alternatives considered

I have considered somehow asking for the encryption keys to other people who were in the room before, but I'm not sure if this works.

### Additional context

Apparently Element Web has this issue also.

I'm not sure if I'm doing anything wrong or not.

This apparently happens specifically inside Spaces, and not every time. I don't know if it is a known issue or not, sorry if this is a duplicate, I searched before :)

**Comment by LinuxinaBit** [comment]
I believe this is intentional.

**Comment by filipesmedeiros** [comment]
@RageGamerBoi but it is technically possible, right? And seems like a very useful option to have as a room admin.

**Comment by kfiven** [comment]
@filipesmedeiros It's technically not possible to share encryption keys of old messages to new room members, so anything before your join you see unable to decrypt. But you are able to see those unable to decrypt messages is because of the room history settings option set to everyone.

**Comment by LinuxinaBit** [comment]
@filipesmedeiros 
> It's technically not possible to share encryption keys of old messages to new room members, so anything before your join you see unable to decrypt.

If it were implemented any other way it would open many opportunities for more exploits and ways to get past the encryption altogether, that's why it's like that.
Remember a room can be replaced, just remove the aliases from the old room, add them to the new one, and make sure people know to join the new one (it's a good idea to set the chat to read only after writing a message about it).

I recommend closing this issue to help clean up the issue tracker unless you want further feedback from others.

**Comment by filipesmedeiros** [comment]
I will close the issue for now. Maybe I will try to come back to it one day :) thanks for all the feedback, y'all!

**Comment by ancatut** [comment]
I was looking into the history messages today and was surprised to see that decrypting old messages in E2EE rooms is actually not possible. Just wondering if anything has changed in that regard, cause it's a pretty crucial thing to be able to have in a space where people come and go!
