### ISSUE TITLE
Window shows "Looks like you have a lot of stuff to heat up!"

### ISSUE THREAD

**Issue by xobs** [ajbura/cinny#1764]
### Describe the bug

When starting Cinny, it just tells me that I have a lot of stuff to heat up.

### Reproduction

1. Launch Cinny

### Platform and versions

```shell
1. OS: Windows 11
2. Browser: Firefox
3. Cinny version: 3.2.1
4. Matrix homeserver: matrix.org
```

**Comment by xobs** [comment]
I put this in "Additional context", however it was dropped.

There doesn't appear to be any way to get additional diagnostic information.

**Comment by xobs** [comment]
I just noticed the 3 dots in the upper-right corner. I selected "Clear cache & reload" and the only thing that happens is the menu disappears. There is no change.

**Comment by kfiven** [comment]
Are you in Firefox incognito mode?

**Comment by xobs** [comment]
I'm not sure why that matters -- I'm running Cinny via `Cinny.exe`, but no I'm not running Firefox in incognito.

**Comment by kfiven** [comment]
Because you provided following in Platform and Versions: 
> 2. Browser: Firefox

Anyways, If you right click and Inspect there would be a console where you could see error.

**Comment by xobs** [comment]
Oh! I was wondering what that question was referring to. I didn't understand what the browser I was using had to do with `Cinny.exe`.

The errors that appear in the Console are:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextBatch')
    at index-eaa22fd4.js:56975:40228
    at async index-eaa22fd4.js:56975:39949
    at async UrA.startClient (index-eaa22fd4.js:57071:26927)
    at async UrA.init (index-eaa22fd4.js:57071:26728)
2index-eaa22fd4.js:37  Uncaught TypeError: Cannot read properties of undefined (reading 'stopClient')
    at UrA.clearCacheAndReload (index-eaa22fd4.js:57071:28511)
    at onClick (index-eaa22fd4.js:57195:11756)
    at Object.sz (index-eaa22fd4.js:37:9301)
    at cz (index-eaa22fd4.js:37:9455)
    at hz (index-eaa22fd4.js:37:9512)
    at mS (index-eaa22fd4.js:37:28783)
    at B8 (index-eaa22fd4.js:37:29200)
    at index-eaa22fd4.js:37:34234
    at Kb (index-eaa22fd4.js:41:18346)
    at rz (index-eaa22fd4.js:37:8467)
```

**Comment by Tcll** [comment]
Well, while this issue relates to Cinny.exe, I just want to mention I am experiencing the same exact thing on multiple LibreWolf instances on separate logins

There are moments where it does load though, and afterwards, all of my sessions have been marked as unverified and are unable to load any encrypted messages

My only saving grace is my co-clients (Nheko) being able to export my keys to import in Cinny, but after the import it still de-syncs (fails to load beyond a certain newer message) and fails to decrypt new messages after the export

I'll create a new issue for this if need be, but it seems like the same issue no less :)

**Comment by Tcll** [comment]
whatever this means might be of help:

![](https://i.sstatic.net/Aunkt48J.png)

**Comment by Tcll** [comment]
**update**

so as it turns out, this may not have been 100% related to Cinny (aside from the errors themselves stopping Cinny from continuing)

The issue was in fact the HDD storing the database, which was formatted with GPT partitioning (modern gparted lied, saying it was "msdos"), and was making random files 0KB when written (also almost corrupting the ext4 superblock) due to the drive being tasked with lots of writes from numerous processes

I've since used an older gparted to format the drive with proper MSDOS partitioning, which shouldn't cause random corruptions like that anymore

Also no, there's nothing wrong with the HDD, it was the drivers behind GPT/EFI partitioning causing the corruptions (this is the 2nd time this has happened now) as this doesn't happen at all when a properly formatted MSDOS drive is tasked with with lots of writes.

So yeah, there you go, my case was the result of GPT partitioning breaking Cinny :P

**Comment by kfiven** [comment]
Closing this one in favor or the linked issue above, both seems same issue.
