### ISSUE TITLE
Mark a room as read upon scrolling to the bottom.

### ISSUE THREAD

**Issue by N-R-K** [ajbura/cinny#184]
#### Is your feature request related to a problem? Please describe.
Simply scrolling to the bottom of a room does not mark it as "read". As far as I can tell, one has to go to the first unread message and then scroll all the way to the bottom for that room to be marked read or manually mark it read from the drop down options.

#### Describe the solution you'd like
I'm not entirely sure if this behavior is intended or not. If it is intended, then I'd suggest marking the entire room as read upon scrolling to the bottom without having to scroll through all the unread messages. 

#### Additional context
When opening a room, maybe automatically start at the first unread message.

**Comment by ajbura** [comment]
@N-R-K if unread separator is loaded with room open then we do focus on it and then one can scroll, but if its deep in history only then Jump to unread show up. And you don’t need to go to top and scroll to bottom or open dropdown, there’s also a button to mark room read in right side of Jump to unread (little check marks).

The reason it was made like this is to prevent marking unread accidentally, discord also does same. Suppose I misclick a room now if I want to read all of the history since last read (something important), I have to do it right now otherwise if I come back later there will not be a Jump to unread button.

**Comment by N-R-K** [comment]
> there’s also a button to mark room read in right side of Jump to unread (little check marks)

Did not notice that. That takes care of my use-case of wanting to mark a room as read easily. Closing.

**Comment by viasux** [comment]
> @N-R-K if unread separator is loaded with room open then we do focus on it and then one can scroll, but if its deep in history only then Jump to unread show up. And you don’t need to go to top and scroll to bottom or open dropdown, there’s also a button to mark room read in right side of Jump to unread (little check marks).
> 
> The reason it was made like this is to prevent marking unread accidentally, discord also does same. Suppose I misclick a room now if I want to read all of the history since last read (something important), I have to do it right now otherwise if I come back later there will not be a Jump to unread button.

The reason discord does this is because they actually have users (unlike matrix). When you're in a chat with more than ~5 people talking at once, it can become very laborious to scroll all the way up and then back down the page, or having to mark the chat as read every time you check it, especially if you keep track of the chat throughout the day, but don't need to read every single message (if you're in a large chat, there's no reason to read every single message).

thats just my opinion on this

**Comment by viasux** [comment]
> @N-R-K if unread separator is loaded with room open then we do focus on it and then one can scroll, but if its deep in history only then Jump to unread show up. And you don’t need to go to top and scroll to bottom or open dropdown, there’s also a button to mark room read in right side of Jump to unread (little check marks).
> 
> The reason it was made like this is to prevent marking unread accidentally, discord also does same. Suppose I misclick a room now if I want to read all of the history since last read (something important), I have to do it right now otherwise if I come back later there will not be a Jump to unread button.

Also, sending a message should mark as read automatically by default, imo, because if you're already interacting with the chat, then you've likely already read everything you wanted to.

Assuming everyone wants to read *every* message before marking a chat as read is incorrect imo & just increases friction for most users.
