### ISSUE TITLE
Multimedia files unable to load due to 401 unauthorized; other clients are fine

### ISSUE THREAD

**Issue by Porkepix** [ajbura/cinny#1961]
### Describe the bug

In different places/chans, I could see many occurrences of media files (pictures, videos) that are not loading, showing a HTTP 401 error, `Failed to load resource: the server responded with a status of 401 (Unauthorized)` in the console.

But checking with other clients did show that those clients were able to load the same medias.

### Reproduction

Go to a channel with medias, and see that they fail to load.

### Expected behavior

These medias should load.

### Platform and versions

```shell
ArchLinux, Cinny 4.2.0 built from source from AUR (https://aur.archlinux.org/packages/cinny-desktop); issue seen on two different computer with similar setup.
```

**Comment by kfiven** [comment]
Use v4.2.1.

**Comment by Porkepix** [comment]
Saw after opening it's probably related to https://github.com/cinnyapp/cinny/issues/1818; but issue seems to state it's fixed so it's unclear to me what's the status considering I can still reproduce this with up-to-date built?

**Comment by Porkepix** [comment]
> Use v4.2.1.

Damn, didn't paid attention 4.2.1 was out. If it fixes that known issue, I guess this can be closed then?

**Comment by kfiven** [comment]
yes

**Comment by mserajnik** [comment]
Commenting this across a few related issue threads for visibility:

---

We upgraded our Synapse instance from a pre-1.11 spec version to the latest one yesterday.
Immediately we also hit this issue in Cinny (using the latest `dev` commit) where authenticated media requests are missing the `Authorization` header.

The `Clear Cache & Reload` button works, but it keeps seemingly randomly breaking afterwards, even with completely fresh browser sessions or different browsers that never had Cinny open before. The problem doesn't happen with Element, suggesting a bug with the MSC3916 implementation in Cinny.

~~According to a debug session with Claude, there might be a race condition with the service worker not being able to append the `Authorization` header in all cases. However, we weren't able to implement a working fix based on this knowledge, even with access token caching directly in the service worker and proactive token updates. We are also not sure if that is actually the problem, because once it breaks for one request it then breaks for all subsequent requests too, hinting towards a deeper issue (if it was a simple race condition, it shouldn't manifest itself for every single request after the first failed one).~~

__Edit:__ It seems like we were able to fix this by changing the service worker to use a single event listener for all messages, see https://github.com/cinnyapp/cinny/commit/5f916814a9890310251712e77a15584315a71a9d (in my fork). If that doesn't fully fix it, it at least alleviates the issue greatly, since none of our users has experienced it since then.
