### ISSUE TITLE
Autocomplete for usernames

### ISSUE THREAD

**Issue by williamkray** [ajbura/cinny#2]
It would be nice to have Cinny autocomplete when typing usernames for people in the room. Currently without a way to view a user's account and only seeing their nick, it's impossible to tag someone.

**Comment by phildenhoff** [comment]
@ajbura I spent a while working on this yesterday. The way Element does autocomplete is very closely coupled with how they do commands, which I think makes a lot of sense (see below) so if you're still working on adding command support and _don't_ get autocomplete for usernames in at the same time, let me know and I'll pick this up so I can build off your work. Otherwise if you haven't made much progress on commands, I'll keep working on what I've started

The below part:
The reason I think it makes sense to tie autocomplete and commands together is that they both need what is essentially a `ContextMenu` for `ChannelViewInput` that can do stuff based on the current message. They both follow the same process: take in the message, parse it to see if it matches a pattern, make suggestions based on the text, and render the suggestions. If you have a different idea, let me know. I'd still be happy to work on this! 😁
