### ISSUE TITLE
Impossible to connect in Firefox Private Browsing Mode with encrypted disk storage

### ISSUE THREAD

**Issue by kidonsky** [ajbura/cinny#20]
**Describe the bug**
While I try to connect with my homeserver account, just after login page, I got an infinite Heating up loading.
And in the console, I can see `Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations.` message.

**To Reproduce**
1. Go to https://app.cinny.in/
2. Fill login, homeserver address and password
3. Click on Connect
3. See infinite Heating up

**Expected behavior**
Connection OK, I can finally test your Matrix client ;D

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser Firefox 90.0.2 

**Additional context**
- I used Incognito mode each times I tried
- ipv6-only homeserver
- I just tried another time after I saw https://github.com/ajbura/cinny/commit/8cf030585f8de9def779af47bbd127455e453799

Thank you !

**Comment by ajbura** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by ajbura** [comment]
A workaround is at https://bugzilla.mozilla.org/show_bug.cgi?id=1639542#c9 but that comes with privacy concerns.

**Comment by e00E** [comment]
This issue should be open. Other web clients like Element work in private browsing mode. If you want to, treat is as a feature request.

**Comment by kfiven** [comment]
Hydrogen doesn't. And treating it as feature request means we stop using IndexedDB, for which there are no plans. And since it's clearly a bug in Firefox, why should we build alternative to hide that bug.

**Comment by e00E** [comment]
It sounds like this is an intentional wont-fix. That wasn't clear to me before, but it is now. That's a reasonable decision.

It would be nice if there was a clearer error message. Currently Cinny hangs and you need to open the console and search for the error message to find this issue thread.

>  Why should we build an alternative to hide that bug?

Assume that all major browsers had a bug that made Cinny unusable. Then it would be reasonable to address the issue in Cinny even though it is technically a bug in the browsers. Whether this makes sense depends on how many users of Cinny are affected and how hard it is to address this Cinny.

You as as a developer can judge when that is and isn't reasonable as you have.

**Comment by notramo** [comment]
The worst thing isn't that it's not working. After all, if someone uses permanent private browsing mode, they can create a separate Firefox profile only for Cinny. That would bring the additional benefit of not having to verify each time the browser is opened.
The worst thing in this bug is that there is no feedback for the user. It should catch the exception, and display a message: 

Cinny doesn't support private browsing in Firefox with encrypted disk.
Possible solutions:
- use normal mode
- use an unencrypted disk
- use a different browser
