### ISSUE TITLE
[Feature Request] URL previews

### ISSUE THREAD

**Issue by reinerh** [ajbura/cinny#284]
#### Is your feature request related to a problem? Please describe.
Please add support for requesting [URL previews](https://spec.matrix.org/v1.1/client-server-api/#get_matrixmediav3preview_url) from the Matrix server.
When links are posted into rooms, it's interesting to see the title, a short description and a thumbnail of the website to decide if I want to open the page and read the whole content.

#### Describe the solution you'd like
When a message containing a link is posted into a room, I'd like cinny to request preview data from the Matrix server (via `preview_url` API) and display an information box below the message that contains the title, a description and a thumbnail (if available).

#### Describe alternatives you've considered
--

#### Additional context
Attached is an example screenshot how Element displays previews.
![preview](https://user-images.githubusercontent.com/3106950/152060384-f80c9cd7-4908-4c07-bfbc-04857a832dec.png)

**Comment by viasux** [comment]
I would love this feature too! However, I think that some notes should be taken from how discord does this.

An **_image/media-only_** url like:
https://the-apothecary.club/_matrix/media/r0/download/t2bot.io/976752106cbe53e7b52fad48cd9c3af3aecec684
previews in discord as a normal image upload would. The same image through element, however, appears like this:
![image](https://user-images.githubusercontent.com/47131867/161680680-f2fdb4c5-77b9-4475-aa32-30f9db7b6158.png)
This creates a bloated user experience, because to actually view the image properly, you have to manually enlarge it - or open the link entirely. There are many reasons someone may not want to open a third party site just to view an image and adding a manual click for something that should be automated seems unnecessary.

Also, links such as:
https://tenor.com/view/sleep-cat-two-cat-cat-cat-love-gif-23651667
which appears like this (in element):
![image](https://user-images.githubusercontent.com/47131867/161681493-a56ff3ca-e547-490d-a762-1ed821a04509.png)

Should also preview similarly, appearing as a simple file upload, just how discord does it.

To be clear, I don't see much wrong with how element does this for non-media url's!

**Comment by cyrneko** [comment]
I wonder, is this something that's being considered for Cinny? This issue has been created quite a while ago, and it seems nothing *official* was said about it :thinking:
