### ISSUE TITLE
Consider renaming "channels" to "rooms"

### ISSUE THREAD

**Issue by ShadowJonathan** [ajbura/cinny#30]
Currently, cinny calls rooms "channels", while I've already poked at this in the TWIM channel when cinny got revealed, I'll file the issue here;

Consider changing the naming of "channels" back to "rooms" to reflect the wider Matrix ecosystem usage of it. The consideration to keep it (imo) is more specialized branding and a better appeal to discord users, but i think that it could confuse users in the terminology, when they talk about channels, and users from other clients talk about "rooms".

Either that, or add an explanatory tooltip somewhere saying that they're synonymous on cinny.

**Comment by vinceTheProgrammer** [comment]
Personally, I like the fact that rooms are called "channels" in Cinny, since, like you mentioned, it'll be easier for Discord users to migrate to Matrix.

But I also understand the importance of consistency across the entire Matrix platform.

What about an option to toggle whether "channels" are named "rooms"? (Of course, the new dilemma would be in deciding which naming style to default to).

Also, I'm behind that tooltip idea 100%.

**Comment by ajbura** [comment]
I knew somebody is going to raise it someday, the reasons we call them channels are,

a) Channel is a widely accepted word when it comes to chat applications. Be it slack/discord/irc, all call them channels.
b) Matrix community know that when people say channels, they are talking about rooms but when it comes to outside community or someone new to matrix, they don't know that rooms means channels.
c) IMO why matrix named them rooms at server level is because the protocol is not just about messaging and it has wide variety of usages but when it comes to use it messaging or chat app, client should take the responsibility and call them channels so there a consistency between chat/messaging applications and it's less confusing to users.

**Comment by ShadowJonathan** [comment]
> Matrix community know that when people say channels

the current technical-heavy matrix community does, but as many more kinds of users join the network, and it becomes friendlier and friendlier to manage and work with, many users won’t even bother thinking about what they’re using, and so little discrepancies become more and more “annoying” as users come from more non-technical backgrounds

> client should take the responsibility and call them channels so there a consistency between chat/messaging applications and it's less confusing to users.

tell that to Element, who are setting the bar and standard for matrix clients atm.

**Comment by ajbura** [comment]
If element does a mistake does that means that every client has to follow that?

**Comment by ShadowJonathan** [comment]
I don't know if there's a notion of "mistake" here, channels != rooms, they named it rooms mainly because element is an ambassador to matrix itself, in many aspects, so it has to be the least confusing of them all.

**Comment by williamkray** [comment]
I think that consistency within the ecosystem is more important than consistency compared to other apps, because this app first and foremost is a _matrix client_ and so therefore should use _matrix terminology_ for it's various concepts. if user A is on Cinny, and user B is on Element, discussing what's happening in another matrix room should be simple for them to do, rather than including confusion because one person calls them rooms and the other person calls them channels.

that being said, if a user is communicating with bridged users on, for example, slack, there is already going to be a certain level of confusion because of the difference in terminology. that is less likely to be a case that would sneak up on users, however, as most people will likely know _when_ they are in a scenario that includes talking to bridged users from another platform (you don't usually do so accidentally, but after rather a lot of setup and configuration).

also, the use of the term `rooms` is nearly as old as the use of the term `channels`: irc predates the term with "channels",  but "chat rooms" have been around since at least the early 1990s.

**Comment by williamkray** [comment]
if there is concern about new user experience for people coming over from Discord etc, then perhaps the actual solution should be a first-time-experience walkthrough, e.g. a popover showing the "room list" (rooms are comparable to channels on slack or discord), here is the user list (click this button to hide it at any time) etc.

**Comment by kfiven** [comment]
I think discussion has run long enough (~ 1 month) and there's a clear consensus that people want room over channel, so we have thought of doing this in upcomming release. 

Also as project will grow, it will be hell of task to do this later.

**Comment by InfiniteWorldSoftware** [comment]
> Personally, I like the fact that rooms are called "channels" in Cinny, since, like you mentioned, it'll be easier for Discord users to migrate to Matrix.

Discord isn't Matrix. People calling chatrooms "rooms" instead of "channels" shouldn't be too hard for the average user to adapt to, and it avoids possible confusion with other chat platforms (also little changes like this run the risk of people thinking of Cinny as a platform just like many people used to think of Riot as a platform (rather than just a client to access a decentralized network) before Element overhauled their marketing).

**Comment by InfiniteWorldSoftware** [comment]
> if there is concern about new user experience for people coming over from Discord etc, then perhaps the actual solution should be a first-time-experience walkthrough, e.g. a popover showing the "room list" (rooms are comparable to channels on slack or discord), here is the user list (click this button to hide it at any time) etc.

There needs to be a way for advanced/returning users to disable this if this is indeed implemented.

**Comment by ShadowJonathan** [comment]
Discord has a "walkthrough" for every user when first logging in, but you can immediately dismiss that by one click of a prompt.

**Comment by williamkray** [comment]
yes, a walkthrough for first-time users should be dismissable, agreed. and it should not happen for the same user multiple times unless they want to go back to the walkthrough again, e.g. there should be a button in settings that says "start first-time user guide" so they can get back to it if they dismissed it on accident or want a refresher.

something similar should be available if there are new features though... but that's getting way off topic.

**Comment by ajbura** [comment]
This is live at https://dev.cinny.in/ Please check it out. (Hope everything works fine.) :P
