### ISSUE TITLE
quickly scrolling room history gets stuck loading messages

### ISSUE THREAD

**Issue by ashkitten** [ajbura/cinny#555]
### Describe the bug

when quickly scrolling up through room history, sometimes cinny will get stuck and not load messages until i scroll back down a bit and up to the top again

### Reproduction

1. scroll as fast as possible up the timeline of a room
2. cinny will get stuck and not paginate more, even though the loading placeholder is there

### Expected behavior

cinny should always paginate when at the top or bottom of the timeline when there are messages to load

### Platform and versions

```shell
os: nixos
browser: firefox 100
cinny version: 2.0.2
```

**Comment by ajbura** [comment]
Hi, I am not able to reproduce it on macOS, firefox.

**Comment by ashkitten** [comment]
i can reproduce reliably by flicking the unlocked scroll wheel on my logitech g502 mouse. here is a video of the bug happening:


https://user-images.githubusercontent.com/9281956/170832489-28a2febc-cf21-494b-a02a-41f4aa5055bc.mp4

**Comment by kfiven** [comment]
@ashkitten Could you please try another account on a different homeserver and see if it happens then?

**Comment by goshhhy** [comment]
i can reproduce this with accounts on two different homeservers.

**Comment by kfiven** [comment]
Would you mind sharing the homeserver so that I can try to reproduce?

**Comment by goshhhy** [comment]
actually, make that three homeservers:

kity.wtf (private)
cybre.space
matrix.org

i can reproduce on both macOS and on Linux, using Firefox. same mouse as @ashkitten has. (cannot scroll fast enough with any other mouse i have)

**Comment by kfiven** [comment]
Tested again with an account on `matrix.org` and `cybre.space` with Firefox 100.0.2 and it works fine.

@goshhhy When it stuck, do you see any errors in browser console?

Also when it is stuck, does it stuck forever or scrolling again fix it?

**Comment by goshhhy** [comment]
there are no errors in the browser console.

when it gets stuck, if you stop scrolling, very rarely it will end up recovering. if it does not, scrolling down until the two placeholder loading messages are no longer visible, then scrolling back up, will fix it.

i have been able to reproduce the issue by running this command within an x11 session, and moving the mouse to the browser window:

```shell
linear@yon ~ $ sleep 3; xdotool click --delay 5 --repeat 2000 4
```

with that script, it will load older messages successfully exactly once, and then get stuck as described / shown.

i have also further tested and been able to reproduce on the latest version of Google Chrome, on Linux.

**Comment by kfiven** [comment]
Ok, I am able to reproduce it by picking the scrollbar with the mouse and sticking it to the top very fast so that it always stays on top.

But I don't think it's a bug as scrolling that fast cause the backfill calculator to panic and it stops calculating the timeline position.

**Comment by ashkitten** [comment]
i'm not sure how this could be considered "not a bug" if normal usage causes this unexpected behavior. regardless of the cause, i run into this issue constantly by just using cinny normally.

**Comment by kfiven** [comment]
Hi, the reason I said that is because I am not able to reproduce this on normal usage. Only when sticking the scrollbar to the top is when this happening for me. And that happens when the scroll calculator panics due to a sudden change of position.

Also, we don't have any errors here and without that, it's almost impossible to know what's wrong happening on your end.

**Comment by ashkitten** [comment]
if you can reproduce it, i don't see why you can't debug the problem on your end. i don't know anything about scroll calculation or why it would panic, but if scrolling too fast makes it stop working then that's clearly a bug.

**Comment by JFronny** [comment]
I have experienced similar behavior when hiding membership events in a room containing very few messages followed by a lot of membership events:
When attempting to view the room, the loading animation plays endlessly, whereas content shows up in element.
The workaround in that case is similar: By repeatedly pressing the "Jump to unread messages" button (if it is available), I can get the latest message to show up (A video of that is attached below).
My (baseless) guess as to why this happens is that cinny tries to load one page of content when the top of the current page is reached, but that event is not triggered here due to different reasons.

https://user-images.githubusercontent.com/33260128/172809434-ed9d512b-044b-4754-b392-21cd4c7f10bb.mp4
