### ISSUE TITLE
Scrollbar is barely visible

### ISSUE THREAD

**Issue by Miepee** [ajbura/cinny#614]
### Describe the bug

The scrollbar is barely visible in every theme.

### Reproduction

1. Go to a room
2. Scroll up

### Expected behavior

1. Scrollbar should be visible at all times
2. Have it be more contrasting against the background

### Platform and versions

```shell
1. OS: Windows 10 21H1
2. Browser: Firefox 99.0.1
3. Cinny version: 2.0.4 (app.cinny.in)
4. Matrix homeserver: matrix.org
```

**Comment by piegamesde** [comment]
Where's Waldo, but with scroll bars:

![image](https://user-images.githubusercontent.com/14054505/193600765-19ac5f9b-965c-4965-bc63-2e419be6b222.png)
![image](https://user-images.githubusercontent.com/14054505/193600809-6e6e0cd0-2c7d-447c-9cc2-f77ffd502735.png)

(IRL these are even harder to spot than on the screenshots because tiny and bad laptop display)

**Comment by GTcreyon** [comment]
This is problematic because it currently uses `--bg-surface-hover` for its default state and `--bg-surface-active` for its hovered state. The next shade up is `--bg-surface-border`, but this breaks on dark mode because it gets darker, not lighter. Would a new color variable be needed?

**Comment by ajbura** [comment]
> This is problematic because it currently uses `--bg-surface-hover` for its default state and `--bg-surface-active` for its hovered state. The next shade up is `--bg-surface-border`, but this breaks on dark mode because it gets darker, not lighter. Would a new color variable be needed?

This has been taken in account [in our new folds design system](https://folds-sb.netlify.app/?path=/story/scroll--vertical) which we are working on implementing in cinny.
