### ISSUE TITLE
Configure default homeserver

### ISSUE THREAD

**Issue by gnouts** [ajbura/cinny#64]
I'd like to selfhost Cinny. I have my own Synapse homeserver.
I'd like to point Cinny to my homeserver by default, so my users don't have to change it everytime they connect.

It would be nice to have an environment variable. As a lot of other projects do : first read env variable in shell, then read a config file, else use default value.

**Comment by BBaoVanC** [comment]
just FYI it can be done right now by editing the source code:

```diff
diff --git a/src/app/templates/auth/Auth.jsx b/src/app/templates/auth/Auth.jsx
index a8837ab..26ec301 100644
--- a/src/app/templates/auth/Auth.jsx
+++ b/src/app/templates/auth/Auth.jsx
@@ -202,7 +202,7 @@ function Auth({ type }) {
                 forwardRef={homeserverRef}
                 id="auth_homeserver"
                 placeholder="Homeserver"
-                value="matrix.org"
+                value="boba.best"
                 required
               />
             </div>
```

**Comment by hifi** [comment]
> It would be nice to have an environment variable. As a lot of other projects do : first read env variable in shell, then read a config file, else use default value.

It's not technically possible for a static hosted web application to read an env variable. It needs to read a config file over XHR like Element does for configuration.

**Comment by gnouts** [comment]
Thanks for the tips @BBaoVanC I'll probably do that in the meantime.

@hifi Ok I didn't know that. I guess a config file is still nice to have.

**Comment by ThisNekoGuy** [comment]
I would appreciate if we just had an option for an edit field in the UI, personally...
Having to rebuild the app (essentially being held responsible for our own updates) as end-users and also not being able to use Vinny with the home servers we already use just because of the landing page is an immediate barrier of entry.

It's not a big deal to casual users who've never used Matrix before, but for others this is very cumbersome. I imagine that was probably what OP preferred (not to assume but as an end-user that would just make sense), but this is obviously only a barrier to those who aren't server hosts like OP is.
@ajbura

**Comment by ajbura** [comment]
@ThisNekoGuy The homeserver field is already editable input. What instance of client are you using? It can be configured to not allow that but on app.cinny.in you sure can enter your homeserver.

**Comment by ThisNekoGuy** [comment]
<img width="1055" height="2201" alt="Image" src="https://github.com/user-attachments/assets/d36e45ff-f9a9-4d78-b071-6642be2bf177" />

It's a preset list dropdown for me on https://app.cinny.in

**Comment by ajbura** [comment]
@ThisNekoGuy ah i see, its the dropdown icon which is causing the confusion. you can click on "matrix.org" and start typing, I am sure it will work.

**Comment by ThisNekoGuy** [comment]
I got the error:
"Failed to login. Unknown reason."

**Comment by ajbura** [comment]
@ThisNekoGuy feel free to open new discussion with more info from console/network tab around the issue you are currently facing.
