### ISSUE TITLE
Commands in text input don't require them to start the line

### ISSUE THREAD

**Issue by hifi** [ajbura/cinny#65]
#### Describe the bug
You can type `something/dm` to get a suggestion for `/startDM/?` which will in fact work if you tab down to it and hit enter. This is unlikely intentional.

#### Expected behavior
Commands `/` and go-to commands `>` would require them to be at the beginning of the line to suggest or work.

**Comment by kfiven** [comment]
I'll just post what I posted in channel for other people to see,

Actually... it's intentional :D

Like commands can be used without deleting the content of msg.

but if you type something/dm, it will not force you to enter command, when there will next space it will be deactivated.

that's why commands are like /join/? (no space)

**Comment by hifi** [comment]
I _think_ this is fine if #75 is implemented as requested so it isn't automatically selected by default.

**Comment by vwkd** [comment]
This would be solved by not overloading one input field for two different jobs, see #129

**Comment by ajbura** [comment]
As per #156 commands now activate at start only.
