### ISSUE TITLE
new-lines in long messages

### ISSUE THREAD

**Issue by lue-bird** [ajbura/cinny#864]
### Describe the problem

Writing longer texts (for me it's explaining code changes), requiring shift+enter for every new-line added is a bit inconvenient and makes me feel uneasy about accidentally sending an incomplete text.

### Describe the solution you'd like

Add a toggle that expands the text edit area and makes enter add a new-line
- mirroring signal's and zulip's behavior:
- if the text area is expanded, enter and shift+enter both always add a new-line and only a click on send closes the text area
- changing the toggle back restores current behavior
- this has also been [suggested in a comment under an issue](https://github.com/cinnyapp/cinny/issues/736#issuecomment-1246942414)

### Alternatives considered

configure send/new-line keyboard actions
  - mirroring slack's behavior:
  - I don't see a setting like this fit in an existing category, so we could for example create "behavior" to which we could also move the markdown setting
  - This is worse than the proposed solution because in most cases, users don't _always_ write longer OR short messages

### Additional context

Used [cinny-desktop](https://github.com/cinnyapp/cinny-desktop) on Ubuntu 22.04.1 LTS
Did I miss something and this already exists?

**Comment by donbex** [comment]
> if the text area is expanded, enter and shift+enter both always add a new-line and only a click on send closes the text area

This option doesn't really feel good to me, since I rather dislike having to switch back and forth between mouse and keyboard. Both Slack and Element have a switch to toggle between Enter to send or Ctrl+Enter to send (or Cmd+Enter on Mac), which is what I would have expected here.

> This is worse than the proposed solution because in most cases, users don't always write longer OR short messages

True, but your preferred solution requires _clicking_ a button to send every short message, which is much less ergonomic than having to press a key chord...

While I don't always write short or long messages, I also don't stick to one or the other within the same conversation, but rather use a mix of the two. I find it much more convenient to use the least amount of keys for the more frequent action, i.e. Enter for new line, since multiple new lines could be added to a message, and a chord to send, since it only needs to be pressed once per message.

**Comment by lue-bird** [comment]
Makes sense. → Let's add a keyboard shortcut for toggling to expanded/collapsed that does the same thing as pressing the toggle with the mouse.
Maybe something like `alt + enter`?

**Comment by Xuanwo** [comment]
> Both Slack and Element have a switch to toggle between Enter to send or Ctrl+Enter to send (or Cmd+Enter on Mac), which is what I would have expected here.

Can we have this toggle in cinny?

**Comment by iedenisov** [comment]
I think a simpler and much more commonly used solution for this one would be having a separate app-wide setting that controls the `Enter` behavior, akin to Telegram as well.

The setting basically chooses whether `Enter` creates **a new line** or **sends the message**; if the former is chosen, the `Ctrl + Enter` combination sends the message instead.
