### ISSUE TITLE
Ability to change font size

### ISSUE THREAD

**Issue by neilalexander** [ajbura/cinny#899]
### Describe the problem

At the moment the text feels quite large on my system compared to other apps. A quick cursory look suggests that a lot of the font sizes are 16px?

### Describe the solution you'd like

It'd be nice if there was a way to control the text size across the UI. A slider or a text entry box in the settings or something.

**Comment by subterfugue** [comment]
I agree. I think it would be a very nice accessibility feature.

**Comment by bja-au** [comment]
Bump - I too would appreciate this being done. Thanks

**Comment by jedomed** [comment]
I made a quick edit that adds a setting for font size: https://github.com/jedomed/cinny

I was bothered that changing to a dark theme also changed the font size and weight (why should it?), so I split it into two settings where more font size options can be added (though a slider would be even better)

this does NOT affect font size for messages and, well, most of the app except for the settings window because I couldn't figure out where the CSS is being generated :-(

![image](https://github.com/cinnyapp/cinny/assets/58390057/927ff398-55d4-4450-b4b3-ff0027e17fee)

**Comment by ajbura** [comment]
this has been added in v4.0.0
